Vagrant.configure("2") do |config|
 	config.vm.box = "bento/ubuntu-20.04"
 	config.vm.provider "virtualbox" do |v|
      v.memory = 2024
      v.cpus = 2
    end
    config.vm.network "forwarded_port", guest: 80, host: 8080, id: "nginx"
    config.vm.network "forwarded_port", guest: 443, host: 4443, id: "nginx-ssl"
end