Vagrant.configure("2") do |config|
 	config.vm.box = "bento/ubuntu-20.04"
 	config.vm.provider "virtualbox" do |v|
      v.memory = 2024
      v.cpus = 3
    end
    config.vm.network "forwarded_port", guest: 19999, host: 19999
 end