version: '3.3'

services:
  nariman-cent:
    hostname: nariman-cent
    container_name: nariman-cent
#    user: 1000:1000
    build: ./build
    restart: always
    ports:
      - "9200:9200"
    volumes:
      - ./data-volume:/usr/share/elasticsearch/data
