version: '3.3'

services:
  nariman-postgres-13:
    hostname: nariman-postgres-13
    container_name: nariman-postgres-13
    user: 1000:1000
    image: postgres:13.0
    restart: always
    ports:
      - "5433:5432"
    cap_add:
      - SYS_NICE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./data-volume:/var/lib/postgresql/data
      - ./test_data:/test_data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: test_database
      POSTGRES_USER: postgres
